apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  namespace: app-backend
  labels:
    app: app-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: app-backend
          image: 381491842895.dkr.ecr.ap-northeast-2.amazonaws.com/cruming-server:latest
          ports:
            - containerPort: 8080