# app/cruming-server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cruming-server-service
  namespace: cruming-server  # 네임스페이스 설정
spec:
  selector:
    app: cruming-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP