controller:
  replicaCount: 2
  nodeSelector:
    kubernetes.io/os: linux
  admissionWebhooks:
    enabled: true
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    externalTrafficPolicy: Local