# apps/cruming-ai/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cruming-ai
  labels:
    app: cruming-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cruming-ai
  template:
    metadata:
      labels:
        app: cruming-ai
    spec:
      containers:
        - name: cruming-ai
          image: minyubo/cruming-ai:latest  # Jenkins가 이 태그를 업데이트할 예정
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cruming-ai-service
spec:
  selector:
    app: cruming-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP