output:
  host: elasticsearch-master.efk.svc.cluster.local  # Elasticsearch 서비스의 클러스터 내부 주소
  port: 9200
  logstash_format: true
  logstash_prefix: kubernetes
  logstash_dateformat: "%Y.%m.%d"

resources:
  limits:
    memory: 500Mi
    cpu: 500m
  requests:
    memory: 200Mi
    cpu: 200m

serviceAccount:
  create: true
  name: fluentd-sa